four-project/formtest/apps/blog/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', index , name='blog_index'),
    path('<int:id>/', PostDetail , name='post_detail'),
    path('create/', CreatePost , name='post_create'),
]

four-project/formtest/formtest/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.blog.urls'))
]

four-project/formtest/apps/blog/models.py
from django.db import models
from  django.contrib.auth.models import User

class Post(models.Model):
    STATUS_CHOICES = [('drf', 'Draft'), ('pub', 'Published')]
    title = models.CharField(max_length=100)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title

four-project/formtest/apps/blog/forms.py
from django import forms
from .models import Post

class PostCreateForm (forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

four-project/formtest/apps/blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post
from .forms import PostCreateForm
# Create your views here.
def index (request):
    posts=Post.objects.all().filter(status='pub')
    context={'posts': posts}
    return render (request, 'blog/index.html',context)


def PostDetail (request ,id):
    try:
        post=Post.objects.get(id=id)
        context={'post':post}
        return render (request, 'blog/detail.html',context)
    except:
        return render (request, 'admin/404.html')


def CreatePost (request):
    context={}
    if request.method == 'POST':
       form=PostCreateForm(request.POST) 
       if form.is_valid():
           form.save()
           return redirect('blog_index')   
    else: 
        form=PostCreateForm()
        context['form']=form
        return render (request, 'blog/create_form.html', context)
    

four-project/formtest/templates/blog/create_form.html
<!-- @format -->

{% extends 'base.html' %} {% block title %} post create{% endblock title %}
{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-9">
      <div class="card shadow my-3 p-5">
        <h3>Add new post:</h3>
        <form method="POST">
          {% csrf_token %}

          <div class="form-group py-2">
            <label class="py-1" for="id_title">post title:</label>
            <input
              type="text"
              class="form-control"
              name="title"
              maxlength="100"
              required
              id="id_title"
            />
          </div>

          <div class="form-group py-2">
            <label class="py-1" for="id_description">post Description:</label>
            <textarea
              class="form-control"
              rows="3"
              name="description"
              cols="40"
              rows="10"
              required
              id="id_description"
            ></textarea>
          </div>
          <div class="form-group py-2">
            <label class="py-1" for="id_author"> post Author:</label>
            <select name="author" required id="id_author">
              <option value="" selected>---------</option>

              <option value="1">admin</option>

              <option value="2">maliheh</option>
            </select>
          </div>
          <div class="form-group py-2">
            <label class="py-1" for="id_status">Status:</label></th>
            <select name="status" required id="id_status">
                <option value="" selected>---------</option>
              
                <option value="drf">Draft</option>
              
                <option value="pub">Published</option>
              
              </select>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
    <div class="col-3">
      <div class="card my-4">
        <h5 class="card-header">About</h5>
        <div class="card-body">
          <p class="card-text">
            We love python and django. So we created a blog site to share our
            thoughts
          </p>
          <a href="#" class="btn btn-sm btn-danger"> More... </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

four-project/formtest/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %} post detail{% endblock title %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-9">
            <div class="card shadow my-3 p-5">
                <h1>{{post.title}}</h1>
                <p class="small text-muted mt-2">By:{{post.author}}</p>
                <p class="mt-2">{{post.date_created}}</p>
                <p class="mt-2">{{post.description}}</p>
            </div>
            <div class="btn btn-sm btn-success"><a class='text-decoration-none text-light' href={% url 'blog_index'  %}>back to list</a></div>
            <div class="card shadow my-3 p-5">
                <h3>Comments:</h3>
                    No comments yet! Be the first one.
            </div>
        
{% endblock content %}

four-project/formtest/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}blog{% endblock title %}
{% block content %}
<div class="container mt-4">
    <div class="row">
      <div class="col-9">
        {% for post in posts %}
        <div class="card shadow-sm my-3">
          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted small py-2">
              {{post.date_created}}
            </h6>
            <p class="card-text py-3">
              {{post.description}}
          
            </p>
            <div class="btn btn-sm btn-success"><a class='text-decoration-none text-light' href={% url 'post_detail' post.id %}>Read More</a></div>
          </div>
        </div>
        {% endfor %}
      </div>
   
      <div class="col-3">
        <div class="card my-4">
          <h5 class="card-header">About</h5>
          <div class="card-body">
            <p class="card-text">
              We love python and django. So we created a blog site to share
              our thoughts
            </p>
            <a href="#" class="btn btn-sm btn-danger"> More... </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}