memoirwriting/apps/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns =[
    path('register/',views.RegisterUserView.as_view(), name='register'),
    path('login/',views.LoginUserView.as_view(), name='login'),
    path('logout/',views.LogoutUserView.as_view(), name='logout'),
    path('profile/',views.ProfileUserView.as_view(), name='profile'),
    path('edit/',views.EditProfileUserView.as_view(), name='edit')

]

memoirwriting/memoirwriting/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("apps.main.urls",namespace='main')),
    path("accounts/",include("apps.accounts.urls",namespace='accounts')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

memoirwriting/templates/accounts_app/editProfile.html
{% extends 'main_template.html' %}

{% block title %}
ویرایش پروفایل 
{% endblock title %}

{% block content %}
<div class="countainer my-3 ">
    <h1 class="text-center text-primary">ویرایش پروفایل </h1>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit", value ="ویرایش " class="=btn btn-primary btn-block">
    </form>
</div>    
  
{% endblock content %}

memoirwriting/templates/accounts_app/login.html
{% extends 'main_template.html' %}

{% block title %}
ورود کاربر
{% endblock title %}

{% block content %}
<div class="countainer my-3 ">
    <h1 class="text-center text-primary">ثبت  نام کاربر</h1>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit", value ="ورود " class="=btn btn-primary btn-block">
    </form>
</div>    
  
{% endblock content %}

memoirwriting/templates/accounts_app/profile.html
{% extends 'main_template.html' %}

{% block title %}
صفحه پروفایل
{% endblock title %}

{% block content %}
<div class="countainer my-3 ">
  <div class="card">
    <h5 class="card-header">{{name}} {{family}} </h5>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item">ایمیل  : {{email}}</li>
        <li class="list-group-item">نام  : {{name}}</li>
        <li class="list-group-item">نام خانوادگی : {{family}}</li>
        <li class="list-group-item">شماره تماس : {{mobile_number}}</li>
        <li class="list-group-item">جنسیت  : {{gender}}</li>
      </ul>
    </div>
    <a href="{% url 'accounts:edit' %}" class="btn btn-success">ویرایش</a>
  </div>
</div>    
  
{% endblock content %}

memoirwriting/templates/accounts_app/register.html
{% extends 'main_template.html' %}

{% block title %}
ثبت نام کاربر
{% endblock title %}

{% block content %}
<div class="countainer my-3 ">
    <h1 class="text-center text-primary">ثبت  نام کاربر</h1>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit", value ="ثبت نام " class="=btn btn-success btn-block">
    </form>
</div>    
  
{% endblock content %}